### PR TITLE
fix: incorrect webhook types

### LINKED ISSUE #372: Webhook Props --Typescript headers
Hello Team,

I am working on typescript project , I can see webhook props typings has some issue in sdk.

Example: How can I pass header like :
"headers": [
{
"key": "key",
"value: "key-value"
"secret": true
}
] -- This throws typescript error

Also inside below properties are mandatory webhook props :
         httpBasicUsername: string;
          httpBasicPassword: string;

Can you please update sdk or let me how to fix this issue.

Thanks

### PR DESCRIPTION
**Pull request by suevalov**
Closes #372 #365 #306

### CODE REVIEW

File: lib/entities/webhook.ts [hunk 1]
```diff
@@ -28,33 +28,36 @@ export type WebhookProps = {
   /**
    * Username for basic http auth
    */
-  httpBasicUsername: string
+  httpBasicUsername: string | null
```
Comment (Khaledgarbaya) [inline lib/entities/webhook.ts:31]: I think this should be `httpBasicUsername?: string` because the property will omitted from the payload if it does not exist

File: lib/entities/webhook.ts [hunk 2]
```diff
@@ -28,33 +28,36 @@ export type WebhookProps = {
...
-  httpBasicPassword: string
+  httpBasicPassword: string | null
 
   /**
    * Headers that should be appended to the webhook request
    */
-  headers: {
-    [key: string]: string
-  }
+  headers: Array<{ key: string; value: unknown; secret?: boolean }>
```
Comment (marcolink) [inline lib/entities/webhook.ts:41]: I'm always uncertain with this, but aren't header values always strings? or, get transformed to string?

Comment (jelz) [reply lib/entities/webhook.ts:41]: Only ASCII strings are accepted for both key and value

File: lib/entities/webhook.ts [hunk 3]
```diff
@@ -28,33 +28,36 @@ export type WebhookProps = {
...
+
   /**
    * Transformation to apply
    */
   transformation?: {
     method?: string
     contentType?: string
     includeContentLength?: boolean
-    body?: object
+    body?: Record<string, any>
```
Comment (jelz) [inline lib/entities/webhook.ts:60]: `body` can be any valid JSON, so `true`, `['test']`, or `123` are valid too

File: lib/entities/webhook.ts [hunk 4]
```diff
@@ -28,33 +28,36 @@ export type WebhookProps = {
...
 
   /**
    * Topics the webhook wants to subscribe to
    */
   topics: string[]
 
+  /**
+   * Webhook filters
+   */
+  filters?: Array<{ [key: string]: any }>
```
Comment (jelz) [inline lib/entities/webhook.ts:51]: I'm fine with that but could be typed better. Will send a link to aschema

File: lib/entities/webhook.ts (hunk 1 above)
Comment (suevalov) [reply lib/entities/webhook.ts]: updated

File: lib/entities/webhook.ts (hunk 3 above)
Comment (suevalov) [reply lib/entities/webhook.ts]: updated

File: lib/entities/webhook.ts (hunk 4 above)
Comment (suevalov) [reply lib/entities/webhook.ts]: updated

File: lib/entities/webhook.ts (hunk 3 above)
Comment (marcolink) [reply lib/entities/webhook.ts]: shouldn't that be of type 

```ts
body?: JsonValue
```

Comment (marcolink) [reply lib/entities/webhook.ts]: I obviously commented on an outdated version 😆 👍
